travis:
  secure:
    BINSTAR_TOKEN: cnrm8xodUMa7gRHtaXfqVuDLAMW3M9rgT3YoPQ79oDQlEz1GDbHAJu+1zhcAbUq8bpoOkyPFoVb+B9CFw9Je5F3olyzBt9odlldAJEr732DGVhX8ownRe6u7ZQFVhfu4D2IzN2lYPkvFTni2nCCZGzD9zVuZYvqD9FCNAdjaHIIR3rV10GOV0sfIjOhNpBrF92VYvFACyg+5IGhB+tcCVOqu/y/MRBoY3W7JbeiRPW8ZtjeIyOnQlyClGERjZivcyyLp1of3RZMJirdc6ZOVLVFX+lOt1Y//osiB2sheuQx/vnBjn8s2a+gKxNgOlAkH2KnqfqpILZW1fOcPKgzX9eUgSPnn1yYWs63AUw3ld01Ax1h0K3MsD1vG/ffiY51VJ7Mr17IaX2aye1j6Gx6JgRN/EdyQjZWff55MJQ4VzoBdSR2DEpKXKBlbr7Gejvr2rGAp4ROlF0R6wHWZYZj25SSA00nQGnaT1oif+UleoO/fu2k5XngtplQFq9IOWQEAyHI/VbRK3jVKetQvRzUlNv7a5i1MK/P1baCDUw6MJuORxnjQcfAtCPr0bwCobEVFiX7Aw5xYrrJVNB0Q6Nt/gleNQmkcZgVzRF2XPCb0WzVZ3T5qngJ26paaSrmvdHxOk/M2HHPXU3hbH+q8GwnSBa9eKZYkiEPChbz8ev9p+rU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
